name: flutter_markdown_example
description: Demonstrates how to use the flutter_markdown package.
publish_to: 'none'

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: '>=1.10.7 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pref_dessert:
    path: ../

flutter:
  uses-material-design: true