name: pref_dessert
description: Package that allows you persist objects as shared preferences easily. Package name comes from Shared PREFerences DESerializer/SERializer of T (generic) class.
version: 0.5.1
homepage: https://github.com/bartektartanus/pref_dessert

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=0.5.3 <1.0.0'
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3
  build_runner: ^1.6.9
  test_api: ^0.2.5
