name: pref_dessert
description: Package that allows you persist objects as shared preferences easily. Package name comes from Shared PREFerences DESerializer/SERializer of T (generic) class.
version: 0.6.0
homepage: https://github.com/bartektartanus/pref_dessert

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  json_annotation: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  build_runner: ^1.12.2
  test_api: ^0.2.0
