name: pref_dessert
description: Package that allows you persist objects as shared preferences easily. Package name comes from Shared PREFerences DESerializer/SERializer of T (generic) class.
version: 0.8.0
homepage: https://github.com/bartektartanus/pref_dessert

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  json_annotation: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  build_runner: ^2.1.7
  test_api: ^0.4.8
